# Generated by Django 4.2.5 on 2023-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='criation_date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='update_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
