version: '3'

services:

  application1:
    depends_on: 
      - data_base
    container_name: 'application-1'
    image: bunoqueiroz/account-manager:1.3.2
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - DEBUG
      - SECRET_KEY
      - HOST
      - PORT
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M

  application2:
    depends_on: 
      - data_base
    container_name: 'application-2'
    image: bunoqueiroz/account-manager:1.3.2
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - DEBUG
      - SECRET_KEY
      - HOST
      - PORT
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M

  data_base:
    container_name: 'data_base'
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 256M

  nginx:
    container_name: 'nginx'
    build: .\nginx-config\
    restart: always
    environment:
      - NGINX_HOST
      - NGINX_PORT
    ports:
      - "80:80"
    depends_on:
      - application1
      - application2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
