version: '3'

services:

  application1: &application1
    depends_on: 
      - data_base
    container_name: application-1
    image: bunoqueiroz/account-manager:1.4.3
    restart: always
    volumes:
      - backup-app:/application/backups/
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - DEBUG
      - SECRET_KEY
      - HOST
      - PORT
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M

  application2:
    <<: *application1
    container_name: application-2

  data_base:
    container_name: data_base
    image: postgres
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 256M

  nginx:
    container_name: nginx
    build: ./nginx-config/
    restart: always
    environment:
      - NGINX_HOST
      - NGINX_PORT
    ports:
      - "80:80"
    depends_on:
      - application1
      - application2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M

  #pgadmin4:
  #  container_name: 'pgadmin'
  #  image: elestio/pgadmin
  #  restart: always
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL
  #    - PGADMIN_DEFAULT_PASSWORD
  #    - PGADMIN_LISTEN_PORT
  #  ports:
  #    - 5050:5050
  #  depends_on:
  #    - data_base
  #  deploy:
  #    resources:
  #      limits:
  #        cpus: '0.2'
  #        memory: 256M

volumes:
  backup-app:
    driver: local
