# Generated by Django 4.2.5 on 2023-09-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('moment', models.DateTimeField(auto_now=True)),
                ('total', models.FloatField(editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
        ),
    ]
