# Generated by Django 4.2.5 on 2023-09-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_account_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, editable=False),
            preserve_default=False,
        ),
    ]
