# Generated by Django 4.2.5 on 2023-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_account_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.FloatField(default=1),
        ),
    ]
