# Generated by Django 4.2.5 on 2023-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='client',
            name='register_date',
            field=models.DateField(auto_now=True),
        ),
    ]
