name: Build and push new versions of the system

on:
  pull_request:
    branches:
      - master

jobs:
  new_image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bunoqueiroz
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: actions/checkout@v4
    - name: building and pushing the new version the account-manager
      env:
        VERSION: ${{ github.run_number }}
      
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install python-dotenv
        python3 scripts/build_and_push_account-manager.py
    