name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the account-manager
      run: docker build . --file Dockerfile --tag account-manager:$(date +%s)
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test a image account-manager
      run: python manage.py test
      
