name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
    
env:
  SECRET_KEY: ${{ secrets.GITHUB_TOKEN.SECRET_KEY }}

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the account-manager
      run: docker build . --file Dockerfile --tag account-manager:$(date +%s)
  
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test a image account-manager
      run: | 
        python3 -m pip install -r requirements.txt
        python manage.py test
    