name: Infra docker compose

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ secrets.DEBUG }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:

  infrastructure:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: bunoqueiroz
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v4
    - name: Docker compose up
      run: |
        docker compose build ./docker-compose.yml
        docker compose up ./docker-compose.yml
      
