name: Infra docker compose

on:
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ secrets.DEBUG }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:

  infra:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: bunoqueiroz
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Up services
      uses: isbang/compose-action@v1.5.1
      with:
        compose-file: "./docker/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          application1
          application2
          data_base
          nginx
          containers_update
  
  tests-prod:
    needs: infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tests Production
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: ./docker-compose.yml
          service: application1
          command: scripts/runtests.sh
