name: Infra docker compose

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_call:

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ secrets.DEBUG }}
  HOST: ${{ secrets.HOST }}
  PORT: ${{ secrets.PORT }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:

  infrastructure:
    runs-on: ubuntu-latest
    steps:          
    - name: Docker compose up

      run: |
        docker compose build . --file docker-compose.yml
        docker compose up . --file docker-compose.yml
