name: Infra docker compose

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:

  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3.0.0
      - name: Docker Login
        with:
          # Username used to log against the Docker registry
          username: bunoqueiroz
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Docker compose build and up
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        run: |
          docker compose build
          docker compose up
